# Change these first
owner: testomatio # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Landing Page
    url: https://testomat.io
  - name: Testomatio App
    url: https://app.testomat.io
  - name: Jira Plugin
    url: https://jira.testomat.io/
  - name: App Assets
    url: https://app-assets.testomat.io/assets/frontend.css
  - name: Testomatio Beta
    url: https://app.testomat.io
  - name: Beta Assets
    url: https://frontend.testomat.io/assets/frontend.css

assignees:
  - davertmik
  - poliarush
  - koushikmohan1996

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.testomat.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars3.githubusercontent.com/u/59105116?s=200&v=4
  name: Testomatio Status
  introTitle: "Status of [Testomat.io](https://testomat.io) Services"
  introMessage: This pages provides real-time status for Testomatio websites
  navbar:
    - title: Testomat.io
      href: https://testomat.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


i18n:
  footer: This is current status of [testomat.io](https://testomat.io)
